# Generated by Django 3.0.6 on 2020-06-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200610_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Meal')),
            ],
            bases=('orders.meal',),
        ),
        migrations.CreateModel(
            name='Pizza_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=128)),
                ('toppings_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Meal')),
            ],
            bases=('orders.meal',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Meal')),
                ('additional_extras', models.BooleanField(default=False)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='orders.Meal_size')),
            ],
            bases=('orders.meal',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Meal')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.Pizza_option')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Meal_size')),
            ],
            bases=('orders.meal',),
        ),
    ]
