# Generated by Django 3.0.6 on 2020-06-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pasta_pizza_pizza_option_salad_sub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cookie',
        ),
    ]
