# Generated by Django 3.0.6 on 2020-06-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_extra_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additive', models.ManyToManyField(blank=True, related_name='in_orders', to='orders.Additive')),
                ('meal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_orders', to='orders.Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('additive_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Additive')),
            ],
            bases=('orders.additive',),
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('additive_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Additive')),
                ('price', models.FloatField()),
                ('additional', models.BooleanField()),
            ],
            bases=('orders.additive',),
        ),
    ]
