# Generated by Django 3.0.6 on 2020-06-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200614_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
